version: '3.5'
services:
  iceslog-web:
    container_name: iceslog-web-docker        # 指定容器的名称
    build:
      context: ../
      dockerfile: Dockerfile
  
    command:
      - sh
      - -c
      - |
        find / -name uvicorn 
        uvicorn iceslog.main:app --host 0.0.0.0 --port 8001
        # /bin/bash -c " while true; do sleep 1; done"

    environment:
      TZ : 'Asia/Shanghai'
    env_file:
      - ../.env
    volumes:
      - ../:/app:rw
    ports:
      - "8001:8001"
    restart: always

networks:
  default:
    name: my-server-network
    external: true

# docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker stop
# docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker rm
# docker images|grep none|awk '{print $3 }'|xargs docker rmi

# docker rmi $(docker images -q | awk '/^<none>/ { print $3 }')


# docker exec -it poker-web-docker /bin/bash