version: '2.2'
services:
  es801:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es801
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data801:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

volumes:
  data801:
    driver: local

networks:
  elastic:
    driver: bridge