"""000

Revision ID: 19b8a292d67b
Revises: f2740d8912b5
Create Date: 2024-06-28 16:21:03.930973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '19b8a292d67b'
down_revision: Union[str, None] = 'f2740d8912b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True))
    op.create_unique_constraint(None, 'user', ['telephone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
